### ISSUE TITLE
immunitet under the flag

### ISSUE THREAD

**Issue by szogi1910** [falahati/veterans#2]
Is it possible to add an immunity to the flag?
For a player who does not meet the requirements he can connect to the server

**Comment by falahati** [comment]
Sorry for the late response, unfortunately, this not possible for now. You can, however, add it to the code very easily. The source code of this plugin is quite simple.

**Comment by falahati** [comment]
`sm_veterans_exclude` and `sm_veterans_include` commands are now available to do exactly this.

I didn't test the latest version since I don't have a server anymore, so it would be great if someone could tell me if it works.
